services:
    _defaults:
        autowire: true
        autoconfigure: true

    Webinteger\OpenWeatherBundle\:
        resource: '*'
        exclude: '../src/{DependencyInjection}'

    webinteger.openweatherbundle:
        alias: Webinteger\OpenWeatherBundle
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'

    webinteger.openweather.cron:
        class: Webinteger\OpenWeatherBundle\Cron\OpenWeatherCron
        arguments:
            - '@contao.framework'
            - '@?logger'
        tags:
            - { name: openweather.cron, method: onHourly }
